baseURL: /
languageCode: ja-jp
title: hattori.dev
googleAnalytics: G-8B5XLER8F7
menu:
  social:
    - name: Twitter
      url: https://twitter.com/yuhattor
      weight: 1
    - name: GitHub
      url: https://github.com/yuhattor
      weight: 2
    - name: LinkedIn
      url: https://www.linkedin.com/in/yukihattori/
      weight: 3
    - name: Email
      url: mailto:hello@hattori.dev
      weight: 8
    - name: RSS
      url: /articles/index.xml
      weight: 9
  main:
    - name: Yuki Hattori
      url: /
      weight: 1
    - name: Twitter@yuhattor
      url: https://twitter.com/yuhattor
      weight: 2
    - name: Content
      params:
        header: true
      weight: 10
    - name: Articles
      url: /articles
      weight: 11
    - name: GitHub Change Feed
      url: /changefeed
      weight: 12
    - name: Links
      params:
        header: true
      weight: 20
    - name: InnerSource Commons
      url: https://innersourcecommons.org/ja
      weight: 21
    - name: InnerSource Patterns
      url: https://patterns.innersourcecommons.org/v/ja/
      weight: 22
    - name: InnerSource YouTube
      url: https://www.youtube.com/channel/UC1R0sxzasCKDcotv4GnCevw
      weight: 23
    - name: InnerSource Twitter
      url: https://twitter.com/InnerSourceJP
      weight: 24
Params:
  description: My Digital Garden on the Internet
  images:
    - /digital-garden-logo.png
  enableSearch: true
  newsletter:
    title: ""
    description: A curated weekly digest once a week to your mailbox
    provider: buttondown
    path: https://buttondown.email/api/emails/embed-subscribe/
markup:
  highlight:
    style: dracula
  goldmark:
    renderer:
      unsafe: true
