name: Create branch and PR on issue open

on:
  issues:
    types: [opened]

jobs:
  create-branch-and-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Create branch and push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git branch blog-${{ github.event.issue.number }}
        git push origin blog-${{ github.event.issue.number }}
    - name: Create file and push
      run: |
        echo ${{ github.event.issue.body }} > issue_body.txt
        git add issue_body.txt
        git commit -m "Add issue body to file"
        git push origin blog-${{ github.event.issue.number }}
    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        title: "Issue #${{ github.event.issue.number }} added to blog"
        head: blog-${{ github.event.issue.number }}
        base: main