name: Create branch and PR on issue open

on:
  issues:
    types: [opened, reopened]

env:
  TZ: 'Asia/Tokyo'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-branch-and-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup git config
      run: |
        git config --global user.email "yuhattor@users.noreply.github.com"
        git config --global user.name "Yuki Hattori"
    - name: Create Branch
      id: create_branch
      run: |
        BRANCH_NAME="blog-${{ github.event.issue.number }}"
        git checkout -b "$BRANCH_NAME"
        git push origin "$BRANCH_NAME"
    - name: Create file and push
      run: |
        cat > tmp.txt << EOF
          ${{ github.event.issue.body }}
        EOF
        git add tmp.txt
        git commit -m "Add issue body to file"
        git push origin blog-${{ github.event.issue.number }}
    - name: Create PR
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.PAT }}
        commit-message: Update report
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        branch: main
        delete-branch: true
        title: '[Sample] Blog Title'
        body: |
          Update report
        labels: |
          blog
        assignees: yuhattor
        reviewers: yuhattor

        # base: main
        # branch: "blog-${{ github.event.issue.number }}"