name: Create branch and PR on issue open

on:
  issues:
    types: [opened, reopened]

env:
  TZ: 'Asia/Tokyo'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-branch-and-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup git config
      run: |
        git config --global user.email "yuhattor@users.noreply.github.com"
        git config --global user.name "Yuki Hattori"
    - name: Create file and push
      run: |
        BRANCH_NAME="blog-${{ github.event.issue.number }}"
        git checkout -b "$BRANCH_NAME"
        cat > tmp.txt << EOF
          ${{ github.event.issue.body }}
        EOF
        git add tmp.txt
        git commit -m "Add issue body to file"
        git push origin "$BRANCH_NAME"
    - run: |
        gh pr create \
        --title "The bug is fixed" \
        --body "Everything works again" \
        --base "main" \
        --head "blog-${{ github.event.issue.number }}" \
        --label "blog" \
        --reviewer "yuhattor" \
        --assignee "yuhattor" \
      # token: ${{ secrets.PAT }}
